### ISSUE TITLE
Files get cropped

### ISSUE THREAD

**Issue by DavidRivers** [pornel/ImageOptim#100]
I'm having the same problem as [this person](http://stackoverflow.com/questions/20116764/imageoptim-brokes-png-files): ImageOptim crops large chunks out of my PNG files when I attempt to compress them. I've tried both batch-processing and doing one at a time, and I get the same result.

The odd thing is that Finder (and Preview) see the images as whole, so perhaps this issue ~~only affects Chrome (or other browsers)?~~ I see the same thing in Firefox.

Here's a screenshot of a part of a webpage where I've tried to place 3 images side-by-side. As you can see, each of these images were clipped greatly (like 90% or so of each file is clipped):

![screen shot 2015-08-17 at 2 28 46 pm](https://cloud.githubusercontent.com/assets/33893/9312711/81d145ae-44ec-11e5-81a8-83ec69a283bb.png)

**Comment by DavidRivers** [comment]
More background: The images are cropped in both Chrome and Firefox. Loading the file with the `file://` protocol shows the correct looking version of the file, however loading the file from my virtual host (as served by the apache web server within my Vagrant virtual machine) shows the broken version of the image.

So, it seems to me that the compression you use within ImageOptim may result in files that for some reason get corrupted when served by apache (or at least with certain configurations of apache, although I think mine has a pretty vanilla config).

**Comment by pornel** [comment]
Can you add to the github issue original and optimized files?

**Comment by DavidRivers** [comment]
@pornel: Sure thing...

Before optimizing:

![digital-ad-fraud](https://cloud.githubusercontent.com/assets/33893/9336659/af352850-45a8-11e5-935b-1bab34c8a7b0.png)
![new-account-fraud](https://cloud.githubusercontent.com/assets/33893/9336660/af371822-45a8-11e5-8158-18fd39090090.png)
![payment-fraud](https://cloud.githubusercontent.com/assets/33893/9336661/af429846-45a8-11e5-9919-3ed49609cf35.png)

...After optimizing:

![digital-ad-fraud](https://cloud.githubusercontent.com/assets/33893/9336688/e44b0122-45a8-11e5-881e-675c2a4ec623.png)
![new-account-fraud](https://cloud.githubusercontent.com/assets/33893/9336687/e448eaae-45a8-11e5-9603-a121e3d714d7.png)
![payment-fraud](https://cloud.githubusercontent.com/assets/33893/9336689/e44f1c12-45a8-11e5-918c-aa7dd0eaee4c.png)

**Comment by DavidRivers** [comment]
...After optimizing:

![digital-ad-fraud](https://cloud.githubusercontent.com/assets/33893/9336776/5edf8caa-45a9-11e5-86f8-70b052becb14.png)
![new-account-fraud](https://cloud.githubusercontent.com/assets/33893/9336775/5edf37f0-45a9-11e5-9730-ff0c9ee2a838.png)
![payment-fraud](https://cloud.githubusercontent.com/assets/33893/9336774/5edefb50-45a9-11e5-9b2f-65895a4ac2ef.png)

**Comment by pornel** [comment]
The files look OK. They're valid and don't have any special chunks or anything suspicious, so I don't see how they could be causing any problems.

But they're all smaller than 1KB, so maybe that's triggering some bug in Apache or some proxy? Do you have any modules or proxies that would try to manipulate images?

**Comment by DavidRivers** [comment]
@pornel: I think this issue was probably a false alarm. After further investigation it seems like my issues with files cropping were probably being caused with my designer's workflow of copying assets from Illustrator into Sketch--and then my attempting to extract those assets from Sketch and optimize them. I'm not sure if ImageOptim was ever at fault here to begin with, but I really appreciate your attention to this issue! Was certainly a blocker at work, but we've fixed our problem. Cheers for a great piece of software, anyway!

**Comment by pornel** [comment]
Phew! :)
