### ISSUE TITLE
Bundled jpegoptim works significantly better (different?) than the stock one

### ISSUE THREAD

**Issue by flyingmutant** [pornel/ImageOptim#102]
On the same source image (4.0M), bundled binary results in 520K file (`-m70 --strip-all --all-progressive`), while stock binary only reduces size to 916K (using same options). This is reproducible with all images I've tried.

Can you please explain how ImageOptim obtains this huge size difference? `jpegtran` in ImageOptim works byte-for-byte the same as stock one.

Bundled version (ImageOptim 1.6.0):
```
jpegoptim v1.4.4beta  darwin
Copyright (c) 1996-2015, Timo Kokkonen

libjpeg version: 6b  27-Mar-1998
Copyright (C) 1991-2014 The libjpeg-turbo Project and many others
```

Stock version (HEAD built with Homebrew):
```
jpegoptim v1.4.4beta  x86_64-apple-darwin14.5.0
Copyright (c) 1996-2015, Timo Kokkonen

libjpeg version: 8d  15-Jan-2012
Copyright (C) 2012, Thomas G. Lane, Guido Vollbeding
```

**Comment by pornel** [comment]
I use MozJPEG which supports trellis quantization and progressive scan optimization.

**Comment by flyingmutant** [comment]
Am I right that MozJPEG has `jpegtran`, but not `jpegoptim`, which is an independent project? So, this huge benefit is just from linking `jpegoptim` with MozJPEG?

BTW, files are visually different (ImageOptim one is "smoother").

**Comment by flyingmutant** [comment]
After a bit of tinkering, I've built `jpegoptim` with MozJPEG, and can now reproduce ImageOptim results.

Gains from linking `jpegoptim` with MozJPEG are enormous indeed (30%+ further file size reduction).

**Comment by aolin480** [comment]
@flyingmutant I know this is really old, and not sure if you remember your process, but I am wondering the same exact thing. If I use my homebrew version vs. the bundled version, the savings is way more with the bundled version. How would I go about building jpegoptim into mozjpeg on my mac?

**Comment by aolin480** [comment]
@flyingmutant a buddy of mine just sent over some awesome instructions, so for future reference, if anyone is looking, here is what was done:

```
# get mozjpeg
wget https://github.com/mozilla/mozjpeg/releases/download/v3.2/mozjpeg-3.2-release-source.tar.gz
tar -xvf mozjpeg-3.2-release-source.tar.gz
cd mozjpeg-3.2-release-source

# build mozjpeg
autoreconf -fiv
./configure
make
sudo make install

# get jpegoptim
git clone https://github.com/tjko/jpegoptim.git
cd jpegoptim.git

# build jpegoptim
./configure CPPFLAGS=-I/opt/mozjpeg/include LDFLAGS=-L/opt/mozjpeg/lib
make
sudo make install

# run it (from terminal)
jpegoptim -V
```
