### ISSUE TITLE
Swedish localisation for "Saved x out of y" missing

### ISSUE THREAD

**Issue by JohanStrandell** [pornel/ImageOptim#103]
The text at the bottom of the main window is not localised when using Swedish. 

I couldn't find the string in the sv.lproj folder, but it should be
"Sparat x MB av totalt y MB. z% per fil i genomsnitt (upp till zz%).

There should be a space between the number and the kB/MB/GB unit (matches Apple's usage in e.g. Finder), but there shouldn't be a space between the number and the percentage sign.

![skarmavbild 2015-08-25 kl 12 20 08](https://cloud.githubusercontent.com/assets/552072/9665723/510a3a5a-5272-11e5-89b4-fa6b04d17515.png)

**Comment by pornel** [comment]
Tack :)
