### ISSUE TITLE
Build failed, unable to checkout a commit in submodule

### ISSUE THREAD

**Issue by stunpix** [pornel/ImageOptim#105]
I'm constantly getting failed builds once `make` tries to update some submodules:

    git submodule init gifsicle
    Submodule 'gifsicle/gifsicle' (https://github.com/pornel/giflossy.git) registered for path 'gifsicle'
    git submodule update gifsicle && touch gifsicle/src
    Cloning into 'gifsicle/gifsicle'...
    fatal: reference is not a tree: c043e4e22b917467be58b6c3cc7cbb51c15b2a7f
    Unable to checkout 'c043e4e22b917467be58b6c3cc7cbb51c15b2a7f' in submodule path 'gifsicle'
    make: *** [gifsicle/src] Error 1
    Command /usr/bin/make failed with exit code 2

I've tried to find commit `c043e4` in master branch of `giflossy` repo, but I can't. Github actually refers submodule to [this tree], which definitely has `c043e4` committed on July 3rd, but [master], (which is cloned by default) is missing that commit. It's not clear for me how this could happen?

[this tree]: https://github.com/pornel/giflossy/commits/c043e4e22b917467be58b6c3cc7cbb51c15b2a7f
[master]: https://github.com/pornel/giflossy/commits/master?page=2

Same with Sparkle and libjpeg submodules.

PS: I'm using Xcode 7 to build

**Comment by pornel** [comment]
Sorry, my bad. I'm rewriting the giflossy patch, so ImageOptim refers to an out of date commit.

**Comment by pornel** [comment]
ef9a0e0ba3e79db725292a66b8fe58781a7411bf

**Comment by stunpix** [comment]
Wow, that was fast! :+1: Thank you!
