### ISSUE TITLE
Build failed, linker can't find _Gif_FullUnoptimize symbol

### ISSUE THREAD

**Issue by stunpix** [pornel/ImageOptim#106]
Linker can't find `_Gif_FullUnoptimize` symbol, because `gifunopt.c` is not in `gifsicle.xcodeproj/Source`. Please add it to project.

**Comment by pornel** [comment]
It should have been removed by the patch file (makefile in gifsicle). I deliberately don't build this feature.

**Comment by stunpix** [comment]
Maybe I missed something, but I don't see any patch in gifsicle. [Here is] a single usage of  `Gif_FullUnoptimize` which leads to such error. I see GIF_NO_UNOPTIMIZE in `ImageOptim/gifsicle/config.h`, but it never under `ImageOptim/gifsicle/gifsicle/*`.

Cold this be a reason?

[here is]: https://github.com/pornel/giflossy/blob/758b0f91c3e2d15659461a5c199e90e6133255cb/src/gifsicle.c#L764

**Comment by pornel** [comment]
Oh, I've accidentally lost that when I moved to submodules. It used to be:

https://github.com/pornel/ImageOptim/blob/783bd065ad5805b728b48b90c45a6698568dfc24/gifsicle/gifsicle-1.64-imageoptim.patch

**Comment by stunpix** [comment]
I also have some issues with updating submodules from Makefiles. They aren't working properly right after cloning from github:
1. Xcode "parallel build" feature must be turned off or it leads to case when several git instances are trying to update different submodules in parallel and one locks main `.git/config` file, so all other git instances are failing to lock it.
2. I found, if submodules are refer to exact commits in external repos, they can't be updated with `git submodule update --depth=1`, because git pulls only last commit from there and then git tries to checkout specific commit that actually wasn't pulled locally. This leads to errors.

Create an issue or send pull request with patches?

**Comment by pornel** [comment]
Yes, patches would be very helpful.

Would you be able to fix .git lock contention without disabling parallel compilation?

Submodules are evil :( Do you think some larger arbitrary depth would be good enough? With depth=1 I've tried to avoid pulling many years of history of multiple projects.

**Comment by stunpix** [comment]
I've checked how `git submodule update --depth=1` works and it (obviously) uses `git clone --depth=1`. Discussion on [stackoverflow] explains why it's not possible with `git clone --depth=1` to pick only exact commit on git servers/clients prior to 2.5. As far as Xcode 7 bundled with git 2.3.8, so we can't get only exact commits from external projects. Perhaps github also uses old git servers. If you want to set bigger depth number to reach exact commit, I'm afraid that one day it again appears unreachable, because of new commits. Seems at the moment there is no other option than remove depth.

[stackoverflow]:http://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository/30701724#30701724

To return parallel builds I propose to add a single download target that runs a single Makefile, that runs all other Makefiles to update/patch submodules. Make will run them sequently. Then we should all relative in xcode projects make depend on this download target, so Xcode's parallel build will be applied to compiling sources not fetching. Maybe not elegant, but should work.

If this is ok, I can do that. :)

**Comment by pornel** [comment]
Thanks for investigating the depth. OK, let's remove it :(

A single target that runs all submodule updates would be good too.

**Comment by stunpix** [comment]
I'm stuck with parallel build. I tried number of ways, but Xcode doesn't allow to call a Makefile before *all* builds. Also not possible to add one target as dependency to several projects at same depth level.

At the moment I see two ways:

1. Do submodule init&update manually right after cloning from github not in Makefiles. Leave Makefiles only for patching, cleaning, downloading gzipped sources and other not related to git stuff.

2. Replace submodules with conventional repos and perform clone&checkout in Makefiles instead of submodule init&update. Then add these subrepo paths to `.gitignore` to avoid collisions with parent ImageOptim repo. This could allow to fetch subrepos in parallel.

Ideas?

BTW, I'm the only who is experiencing these issues?

**Comment by pornel** [comment]
I'd prefer option 2, since ideally I'd like Xcode's "Run" to actually run ImageOptim in a freshly cloned repo, so that it's possible to start hacking without RTFM and build errors.

Another option perhaps may be to try locking? Init submodules via a shared shell script that waits if another copy of it is running?

**Comment by stunpix** [comment]
Agree with you: script with lock file will be best solution.

I have sent a pull request. :)

**Comment by pornel** [comment]
Fixed #110
