### ISSUE TITLE
Wrong App ID for ImageOptimize extension

### ISSUE THREAD

**Issue by stunpix** [pornel/ImageOptim#109]
Xcode 7 complains about App ID of ImageOptimize extension target:

```
An App ID with Identifier 'net.pornel.ImageOptim.ImageOptimize' is not available. Please enter a different string.
```

Renaming App ID to `net.pornel.ImageOptimize` fixes this error.

**Comment by pornel** [comment]
Changed in 1.6.1: https://imageoptim.com/changelog.html
