### ISSUE TITLE
Not Working on El Capitan 10.11

### ISSUE THREAD

**Issue by soso2247** [pornel/ImageOptim#113]
ImageOptim will launch at El Capitan but window won't appear at all.

**Comment by mathiasbynens** [comment]
Works for me.

**Comment by pornel** [comment]
You need to be more specific. What version of ImageOptim? Is there any error in Console.app?

I've developed the latest version on El Capitan and built it using 10.11 SDK, so it works for me.

**Comment by soso2247** [comment]
I'm using 1.6.0 and at console.app there was these errors.

(these might not all about imageoptim)

10/6/27 H 12:31:21.112 AM pkd[418]: UNINSTALLED:net.pornel.ImageOptim.ImageOptimize net.pornel.ImageOptim.ImageOptimize(1.0) 225B83CD-6D6F-465D-8269-B568E8D8C831 /Applications/ImageOptim.app/Contents/PlugIns/ImageOptimize.appex
10/6/27 H 12:31:21.170 AM pkd[418]: INSTALLED:net.pornel.ImageOptim.ImageOptimize net.pornel.ImageOptim.ImageOptimize(1.0) <__NSConcreteUUID 0x7fc233e1e0d0> 1A2B23AF-595B-4AE1-A562-4629C6770E82 /Applications/ImageOptim.app/Contents/PlugIns/ImageOptimize.appex
10/6/27 H 12:31:21.186 AM taskgated[128]: no application identifier provided, can't use provisioning profiles [pid=3663]
10/6/27 H 12:31:21.368 AM ImageOptim[3663]: Failed to connect (progressBar) outlet from (ImageOptimController) to (NSProgressIndicator): missing setter or instance variable
10/6/27 H 12:31:21.000 AM kernel[0]: ImageOptim[3663] triggered unnest of range 0x7fff9b200000->0x7fff9b400000 of DYLD shared region in VM map 0xf6c05d192bf1a769. While not abnormal for debuggers, this increases system memory footprint until the target exits.
10/6/27 H 12:31:21.453 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=5
10/6/27 H 12:31:21.453 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=6
10/6/27 H 12:31:21.454 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=7
10/6/27 H 12:31:21.454 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=8
10/6/27 H 12:31:21.454 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=9
10/6/27 H 12:31:21.454 AM ImageOptim[3663]: CUIThemeStore: No theme registered with id=10
10/6/27 H 12:31:21.474 AM com.apple.usbmuxd[82]: HandleUSBMuxDictionary client 0x7fd4a8412150-duet/NULL using library 1.4.0, running usbmuxd-364
10/6/27 H 12:31:21.474 AM com.apple.usbmuxd[82]: LOCKDOWN_V2_BONJOUR_SERVICE_NAME is _apple-mobdev2._tcp,96c1083c
10/6/27 H 12:31:21.558 AM ImageOptim[3663]: Results cache is in /Users/LEo/Library/Caches/ImageOptimResults.db
10/6/27 H 12:31:21.643 AM ImageOptim[3663]: *** Assertion failure in CGImageBlockSetRef __csiCompressImageProviderCopyImageBlockSetWithOptions(void *, CGImageProviderRef, CGRect, CGSize, CFDictionaryRef)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-362/CoreTheme/ThemeStorage/CUIThemeRendition.m:982
10/6/27 H 12:31:21.643 AM ImageOptim[3663]: CGImageBlockSetRef __csiCompressImageProviderCopyImageBlockSetWithOptions(void *, CGImageProviderRef, CGRect, CGSize, CFDictionaryRef) unknown pixel format 0
10/6/27 H 12:31:21.646 AM ImageOptim[3663]: (
	0   CoreFoundation                      0x00007fff980f4bd2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff98e1b4fa objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff980f98aa +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff8afe4b1e -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   CoreUI                              0x00007fff8b4b10bf __csiCompressImageProviderCopyImageBlockSetWithOptions + 562
	5   CoreGraphics                        0x00007fff9cd5f0a8 CGImageProviderCopyImageBlockSetWithOptions + 132
	6   QuartzCore                          0x00007fff9baf208c _ZN2CA6Render12create_imageEP7CGImageP12CGColorSpacej + 1115
	7   QuartzCore                          0x00007fff9baf1992 _ZN2CA6Render10copy_imageEP7CGImageP12CGColorSpacejd + 395
	8   QuartzCore                          0x00007fff9bafdd05 _ZN2CA6Render13prepare_imageEP7CGImageP12CGColorSpacejd + 9
	9   QuartzCore                          0x00007fff9baed040 _ZN2CA5Layer14prepare_commitEPNS_11TransactionE + 354
	10  QuartzCore                          0x00007fff9baebe58 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 288
	11  QuartzCore                          0x00007fff9baeba98 _ZN2CA11Transaction6commitEv + 508
	12  QuartzCore                          0x00007fff9baf728f _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 71
	13  CoreFoundation                      0x00007fff98089e07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	14  CoreFoundation                      0x00007fff98089d77 __CFRunLoopDoObservers + 391
	15  CoreFoundation                      0x00007fff98068d58 CFRunLoopRunSpecific + 328
	16  HIToolbox                           0x00007fff9b1d3d55 RunCurrentEventLoopInMode + 235
	17  HIToolbox                           0x00007fff9b1d3a97 ReceiveNextEventCommon + 184
	18  HIToolbox                           0x00007fff9b1d39cf _BlockUntilNextEventMatchingListInModeWithFilter + 71
	19  AppKit                              0x00007fff8dbe8f3a _DPSNextEvent + 1067
	20  AppKit                              0x00007fff8dbe8369 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	21  AppKit                              0x00007fff8dbdcecc -[NSApplication run] + 682
	22  AppKit                              0x00007fff8dba6162 NSApplicationMain + 1176
	23  ImageOptim                          0x000000010d3d394c ImageOptim + 6476
	24  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by Vmadmax** [comment]
Works for me with Version 1.6.0a4

**Comment by pornel** [comment]
The log indicates that the crash happens in Apple's "CoreUI/CoreUI-362/CoreTheme/ThemeStorage/CUIThemeRendition.m" when the user interface is drawn by the system.

Unfortunately, I can't reproduce the problem, so I have no idea what needs to be fixed :(

Maybe check if the beta version works: https://imageoptim.com/ImageOptim1.6.1a1.tar.bz2

**Comment by mikewink** [comment]
I have a similar problem with ImageOptim on El Capitan 10.11.1. The application won't open and the dialog that comes up just suggests that the application is broken and should be trashed. I downloaded both available versions, same result.

**Comment by pornel** [comment]
There are too many unrelated issues mentioned in this ticket.

I develop ImageOptim in El Capitan and that's the only system version that I'm 100% certain it works on. For specific problems, please report issues more specific than "doesn't work".
