### ISSUE TITLE
backup files created when using command-line execution

### ISSUE THREAD

**Issue by kudit** [pornel/ImageOptim#116]
Probably due to some old setting that isn't present anymore, when I run imageOptim from the command line like this (per instructions at https://imageoptim.com/command-line.html):

    /Applications/ImageOptim.app/Contents/MacOS/ImageOptim .

Backup files named ~bak are created.  Is there a way to prevent these backup files from being created?

**Comment by pornel** [comment]
~bak files are created when Trash on your system doesn't function properly. Are you using a network drive or something like that?

**Comment by kudit** [comment]
Nope.  But the directory I'm in is in /Library/WebServer/Documents/ and running from Apache, so that may have something to do with it?  I ended up adding a cleanup step to my script that deletes those files, but it would be nice not to have to do that.

**Comment by pornel** [comment]
Ah, yes. Apache user may not have permission to write to `~/.Trash`.

Currently the logic for this is hardcoded. It was written for regular GUI users in mind. I wouldn't want anybody to lose their files when an unexpected write error happens.
