### ISSUE TITLE
improvement request -  background conversion

### ISSUE THREAD

**Issue by SalvaP** [pornel/ImageOptim#120]
Can you can add an option to convert the file using fewer resources?
in order to avoid switching on the processor fan

**Comment by pornel** [comment]
That's very unlikely. 

Image optimization is by its nature a very intensive process. Spreading it over time would make it take *very* long.

There's also difficulty in figuring out when to stop and how long to wait for the CPU to cool down - it depends on CPU temperature, outside temperature, and what other processes are doing in the system.

**Comment by pornel** [comment]
Similar to #118
