### ISSUE TITLE
Support JPEGmini?

### ISSUE THREAD

**Issue by mathiasbynens** [pornel/ImageOptim#38]
Would it be possible to support [JPEGmini.app](http://www.jpegmini.com/app) when it’s installed?

I noticed that after shrinking images using JPEGmini.app, ImageOptim can usually still save a few bytes. If ImageOptim could somehow trigger JPEGminification, it would save some time going back and forth between the two apps.

**Comment by gingerbeardman** [comment]
It seems that if you use JPEGmini on a JPG it leaves some metadata that it has been processed, so that it will refuse to process that image if you try again. Passing that JPG through ImageOptim removes that metadata.

**Comment by pornel** [comment]
https://github.com/JamieMason/ImageOptim-CLI supports JPEGMini, but that integration is hard to implement and maintain as JPEGMini doesn't have a supported method to do this. 

ImageOptim now supports MozJPEG. I know it's not quite the same thing, but it's a decent option if you want to lower quality of JPEGs.

Given that, I'd rather not support JPEGMini.

**Comment by gingerbeardman** [comment]
Fair comment, particularly as JPEGmini doesn't have a nice way to do this (I've requested they add ability to launch the app)

But really I don't think MozJPEG is comparable and definitely not a replacement for JPEGmini.
