### ISSUE TITLE
Ability to distribute work to other computers on your LAN

### ISSUE THREAD

**Issue by rjmunro** [pornel/ImageOptim#43]
Some of the tools can probably be run on other computers on the LAN using ssh and piping the image data over the connection. When optimising hundreds of images on an old site, this could massively speed the process.

This probably needs quite a bit of discussion on the details of how it would work.

**Comment by fulldecent** [comment]
Recommending to close issue as out of scope for this project.

However, as a way to implement this for your use case, and would be cool to continue discussing here, please look into the `parallel` command which can do this.

**Comment by pornel** [comment]
While it's not too hard to run a tool via SSH, doing it *well* to the point it "just works" is pretty hard. I think I'll leave it out of scope of ImageOptim.
