### ISSUE TITLE
Add support for mozjpeg

### ISSUE THREAD

**Issue by kokarn** [pornel/ImageOptim#45]
Mozilla has introduced another compression algorithm, mozjpeg.
https://blog.mozilla.org/research/2014/03/05/introducing-the-mozjpeg-project/

It might be a good compliment to the other algorithms already available but i haven't seen any real-world tests or comparisons yet.

Heres the source for you.
https://github.com/mozilla/mozjpeg

**Comment by pornel** [comment]
Done in 1.6 (for lossless)
