### ISSUE TITLE
Images break Philips Photo Frame

### ISSUE THREAD

**Issue by evanchiu** [pornel/ImageOptim#78]
I blame Philips, not ImageOptim, but when there are any images that have been compressed with ImageOptim on the Photoframe. It freezes as soon as it starts trying to show a slideshow, just a black screen with a clock, totally unresponsive to the buttons.

I wrote reviews at [Best Buy](http://www.bestbuy.com/site/philips-8-lcd-digital-photo-frame/9652119.p?id=1219427364957) and [Philips](http://www.usa.philips.com/c-p/SPF3483_G7/home-essentials-digital-photoframe/reviewandawards#), but anyone savvy enough to use ImageOptim is probably savvy enough to realize the Photoframe couldn't handle it.

Keep up the good work!

**Comment by pornel** [comment]
Oh, that's unfortunate.

I guess that disabling `jpegrescan` in prefs will help — that's the most effective JPEG optimization, but since it uses less common JPEG features, it also tends to expose bugs most often.
