### ISSUE TITLE
Question about the algorithm

### ISSUE THREAD

**Issue by eGavr** [pornel/ImageOptim#79]
Hi!

Have I understood the algorithm correctly:

The file is minimized by all algorithms and I receive the best result of one of them? 

?

**Comment by pornel** [comment]
Yes, always the smallest result is chosen.

**Comment by eGavr** [comment]
Thanks for the quick reply ;)

**Comment by mathiasbynens** [comment]
And if the original file size is smaller than the “compressed” result, the original will be used. (This sounds like a no-brainer, I know; but some compressor tools such as pdfsqueeze don’t do this.)

**Comment by eGavr** [comment]
Thanks ;)

**Comment by eGavr** [comment]
And I have one question about `zopflipng`, to be more exact about `alternativeStrategy` option. It becomes `true` if I try to compress file the second time?

**Comment by pornel** [comment]
Yes. The idea is to avoid running exactly same algorithm twice. It's done only when user requests another run, since running both strategies is very slow and usually not worth it.

**Comment by eGavr** [comment]
And can you give me advices, as the author of `zopflipng`, about what split strategy to use for files. Maybe there is any algorithm that can help to understand what strategy to use?

**Comment by pornel** [comment]
I'm not author of zopflipng. I've only patched it to work with larger files.

I'm not sure if I fully understand split strategies. Try both, see which one is usually better?

**Comment by eGavr** [comment]
Okey) Thanks. I'll try to figure it out.

**Comment by eGavr** [comment]
Do you use `pngquant` in `imageOptima`?
It seems 'Yes', but there are no any possibilities to configure it using CLI interface.

**Comment by pornel** [comment]
I include it to help ImageOptim-CLI, but I don't expose it in the UI because of #17

**Comment by eGavr** [comment]
Thank you ;) As I've understand, `ImageAlpha` really uses it, but not `ImageOptim`,  because the compression is not safe?

**Comment by pornel** [comment]
Yes

**Comment by eGavr** [comment]
And again, one more question about the algorithm.

I have a raw file `1.png`
It is compressed by one of the algorithms.
The next algorithm will compress the result of the previous one or the raw file again?

**Comment by pornel** [comment]
Depends. If there are many files, then they'll be chained. If there are fewer files than CPU cores, then they'll use raw source again.

**Comment by eGavr** [comment]
But what order do you use?

It seems that using two algorithms by chain,  but in different order,  gives various results

**Comment by pornel** [comment]
Yes, it varies.

**Comment by eGavr** [comment]
And how do you detect the best chain? It seems, that it is impossible to check all chains. The compression will become very-very slow

**Comment by pornel** [comment]
It's an unsolved problem. The "Again" button helps sometimes.

**Comment by eGavr** [comment]
But what chain do you use firstly?

Or these chains are generated randomly every time?

**Comment by pornel** [comment]
Read the code?

**Comment by eGavr** [comment]
Not good enough in this programming language yet (

Please,  where can I look?

**Comment by pornel** [comment]
Rules for starting programs are here https://github.com/pornel/ImageOptim/blob/113c2d27b91153e27e06b03da67d7360dba056ac/imageoptim/File.m#L451-607

**Comment by eGavr** [comment]
Thank you very much ;)

I'm sorry for the trouble delivered.

**Comment by pornel** [comment]
No problem :)

**Comment by eGavr** [comment]
I have a task to optimize PNG files as much as possible and it seems that the chain:

```
advpng -> optipng -> pngcrush -> pngout -> zopflipng
```

gives better result than the chain that is used:

```
pngcrush -> optipng -> zopflipng -> pngout -> advpng
```

**Comment by pornel** [comment]
pngcrush removes gamma, zopflipng clears alpha channel, so they should be earlier in the chain.

**Comment by eGavr** [comment]
Ohhh... So, it is functionally vital to use exactly chain that you've use, is not it?

**Comment by pornel** [comment]
Depends what you're trying to do. See http://css-ig.net/png-tools-overview

**Comment by eGavr** [comment]
Thank! will be looked through.

And I hope I am going to ask the last silly question:

According to this code https://github.com/pornel/ImageOptim/blob/113c2d27b91153e27e06b03da67d7360dba056ac/imageoptim/File.m#L489-L496

```worker_list``` becomes [pngcrush, optipng, zopfli,  pngout, advpng]

But you've said that firstly ```pngcrush``` and then ```zopfli``` are run.
And when I start the CLI side of `ImageOptim` I really see that firstly ```pngcrush```  and then ```zopfli```` compresses files.

So... what's the real chain?) 

The code says: pngcrush -> optipng -> zopfli -> pngout -> advpng

**Comment by pornel** [comment]
Workers are added to a queue, which can run them all at the same time if there isn't enough work to do to keep all CPU cores busy.

**Comment by eGavr** [comment]
Thanks! I'm satisfied with the answer)

**Comment by eGavr** [comment]
`zopflipng` does not work on linux. (
Is there any patches? Seems it is one of the most powerful one,  but it's a pity that it can be used only on MAC because of a `dispatch` module.

**Comment by pornel** [comment]
Use official zopfli on linux

**Comment by eGavr** [comment]
But you have change a lot,  have not you?

**Comment by pornel** [comment]
I've only changed performance of the tool, but not compression algorithm

**Comment by eGavr** [comment]
What about lots of useful options for example `keep-chunks` or `splitting`?
Is it very expensive to support both platforms?

**Comment by pornel** [comment]
`dispatch_async` works on FreeBSD :)

I'm focused only on OS X at the moment.

**Comment by eGavr** [comment]
The problem is that `dispatch` is provided only for MAC

**Comment by pornel** [comment]
…and freeBSD. 

I'm not going to port that to Linux.

**Comment by eGavr** [comment]
And it is absolutely your right to do so ;) 
Thank you very much.
Great tool (for MAC,of course^^)

**Comment by pornel** [comment]
Don't bother with my fork. Just use the official version. My fork does not improve compression.

**Comment by eGavr** [comment]
Probably I should say why I need only your fork)
Your tool `ImageOptim` is so great, so I need to write a linter for it. To be more exact, there is a task which sounds something like this "Check whether the file was optimized by ImageOptim".
The written script should be run on UNIX, so I can not really solve my problem by writing something else ;(

**Comment by pornel** [comment]
You don't need my fork. It does not change compression.

**Comment by eGavr** [comment]
I am sorry for repeating, but it seems that you have added lots of options and use them in `IamgeOptim`, for example `keepchunks`. 
This option influences on the compression results, does not it?

**Comment by eGavr** [comment]
I've made two pull requests,  I'll be very grateful if you review them.
https://github.com/pornel/zopfli/pull/1
https://github.com/pornel/zopfli/pull/2

**Comment by eGavr** [comment]
Does `pngrush.patch` influences on the compression results of the raw `pngcrush tool`?
It seems that it does some refactoring but after using this patch the `make` command fails when I've tried to do this manually.

**Comment by pornel** [comment]
The patch only removes features I don't use.

**Comment by eGavr** [comment]
Probably I am doing something wrong, because after applying of a patch which removes the variable `new_mng` , the compiler fails with log that `new_mng` is used but not declared.

**Comment by pornel** [comment]
Yes, because I don't have MNG support enabled.

**Comment by eGavr** [comment]
Probably there is some misunderstanding... As I've already said before, I need to lint your tool (many developers in our team forget to use it and pushes uncompressed files on github, so there is idea to check files on compression by ImageOptim), so I need to copy the behaviour of algorithms.

I've downloaded `pngcrush` using **curl** and applied your patch then I've run `make` in order to get binary file, but the compilation failed because of the above written problem.

**Comment by pornel** [comment]
1. You're falsely assuming that you need to do _exactly_ what ImageOptim does to check if images have good compression

2. Please don't use my patches, they're for needs of ImageOptim specifically and I'm not willing to support them outside the app.

**Comment by eGavr** [comment]
> You're falsely assuming that you need to do exactly what ImageOptim does to check if images have good compression

You are absolutely right.
But we all use ImageOptim and I've received the concrete task whether it was used on the file.

> Please don't use my patches, they're for needs of ImageOptim specifically and I'm not willing to support them outside the app.

Yes, of course. 
I'm really sorry for making you so many troubles and wasting your time; I am just trying to do what my team leaders want from me( and I've helped me a lot for this ;)

**Comment by eGavr** [comment]
Compressed a file with ImageOptim,  received the result,  tried to compress it further - the file can not be compressed,  but using the pure zopflipng from a command line with the same options I've managed to receive a better result, why?

**Comment by pornel** [comment]
Zopfli has element of randomness, so you'll always be able to compress slightly better, if you try long enough.

ImageOptim limits number of iterations in Zopfli, and I think it's smaller than the default.

**Comment by eGavr** [comment]
Yes, I've already understood this,  but I've tried to use exactly the same number of iteration as in ImageOptim, but still recieved the smaller result, I've even set `iterations=1`, but the result using the pure zopfli was better again.

**Comment by eGavr** [comment]
Oh.  I've understood the reason. And it seems strange to me.

I've used zopflipng which works on Linux (I've just use your code from previous commits before you've used `dispatch`) and this previous variant works better.
