### ISSUE TITLE
Move website to Github

### ISSUE THREAD

**Issue by sandstrom** [pornel/ImageOptim#86]
Entirely up to you of course, but if the website was on Github people could easily contribute to it.

*The source that is (I'm not thinking about Github pages).*

**Comment by pornel** [comment]
The site is built using a bunch of hacky scripts that probably only work on my machine, so I doubt it'd be useful to anyone.

**Comment by sandstrom** [comment]
I understand. Just to be clear, it wasn't so it would be useful to others, it was so others could help you refine/work on the website. Similar to how many other open-source projects keep their website on Github — for more contributions.
