### ISSUE TITLE
imagemin performance

### ISSUE THREAD

**Issue by bensquire** [pornel/ImageOptim#87]
I stumbled across this and found it managed to optimise my PNG images (in some case substantially) more than imageOptim...

https://github.com/imagemin/imagemin-app

Didn't know if it was worth a look?

**Comment by pornel** [comment]
Can you share images that it optimises more?

imagemin includes optipng, gifsicle and jpeggran, which are in ImageOptim already.

**Comment by bensquire** [comment]
This image is ~294KB and imageoptim can't reduce it any further (everything on the highest settings apart from optipng which is on the 3rd "notch")

![manga](https://cloud.githubusercontent.com/assets/600237/7489324/60492fca-f3cd-11e4-8dba-8e234d1ca5d6.png)

This is the image after I've put it though imagemin:

![manga](https://cloud.githubusercontent.com/assets/600237/7489353/adf31088-f3cd-11e4-8251-21dc445a2a86.png)

Its 158KB in size. I don't see any detectable reduction in quality (I'm assuming its lossless).

This might be a red herring but imagemin was FAST, on my machine this image was done in <8s in imagemin but took nearly 45s in imageoptim.

1 last thing, putting the imagemin optimised image back into imageOptim, reduced the size again down to 148Kb :confused:

**Comment by pornel** [comment]
Oh, but the images are different. It seems that imgmin also used something equivalent to ImageAlpha.

**Comment by bensquire** [comment]
Now you've said that I can see differences in colour....

**Comment by pornel** [comment]
In that case please help me design UI for lossy optimizations so ImageOptim can have such compression built-in: #17

**Comment by denji** [comment]
SIMD version jpegtran: https://github.com/cloudflare/jpegtran
* https://blog.cloudflare.com/doubling-the-speed-of-jpegtran/
