### ISSUE TITLE
Transparency lost

### ISSUE THREAD

**Issue by zloyeb** [pornel/ImageOptim#88]
Randomly loosing transparency in some PNGs after being 'chewed' by ImageOptim

Out of about 80 files dozen random files are no longer transparent. They either get black or white background.

- I've tried playing with settings and aggressive levels - no luck
- OSX Preview not displaying this bug (still shows transparency like everything is ok). But thsese added backgrounds visible in photoshop, Google Drive and android dev tools/devices themselves.

**Comment by pornel** [comment]
I think the main problem is grayscale+alpha mode, so I'm going to remove it: #89
