### ISSUE TITLE
What compression algorythm does ImageOptim use?

### ISSUE THREAD

**Issue by sikko** [pornel/ImageOptim#90]
Thanks for this software that is simple and does just what we need.
Some images shrink from 5MB to 1MB while some others go from 5MB to 4MB.
So I took that same image and used https://compressor.io and it went down to 1.4MB in lossless compression.
So I wondered what compression algorythm does ImageOptim use? and if the features of https://compressor.io could be ported to ImageOptim.

**Comment by pornel** [comment]
AFAIK compressor.io uses pngquant, which is lossy. See #17
