### ISSUE TITLE
[suggestion] Better command to run from bash scripts or build systems

### ISSUE THREAD

**Issue by vitorgalvao** [pornel/ImageOptim#92]
On the [command-line page of the website](https://imageoptim.com/command-line.html), you suggest `/Applications/ImageOptim.app/Contents/MacOS/ImageOptim *.png` to “run ImageOptim from bash scripts or build systems”. That, naturally, only works if ImageOption is installed to `/Applications`.

Changing the command to `"$(mdfind kMDItemCFBundleIdentifier = net.pornel.ImageOptim)"/Contents/MacOS/ImageOptim *.png` makes sure that it always runs, independently of ImageOptim’s location.

**Comment by pornel** [comment]
Thanks, but I prefer the simpler variant, since it's easy to figure out that the path may need to be changed. 

The smarter version may cause problems when there are multiple copies, when Spotlight is disabled, etc.
