### ISSUE TITLE
Run without calling the GUI at all?

### ISSUE THREAD

**Issue by vitorgalvao** [pornel/ImageOptim#93]
Would it be possible to run ImageOptim without calling a GUI at all? Currently, it seems like the best we can do is call it with a hidden GUI, that still shows its icon in the dock. I was wondering it was possible to have it run entirely on the command-line.

**Comment by pornel** [comment]
No, unfortunately it's currently not possible.

If you need truly headless operation then I suggest calling yourself the same tools that ImageOptim uses.
