### ISSUE TITLE
When started via cli, error warning

### ISSUE THREAD

**Issue by kud** [pornel/ImageOptim#98]
`2015-08-17 15:36:52.156 ImageOptim[51157:1356427] Failed to connect (progressBar) outlet from (ImageOptimController) to (NSProgressIndicator): missing setter or instance variable`

**Comment by nicholaelaw** [comment]
I'm getting the warning too:

    $ /Applications/ImageOptim.app/Contents/MacOS/ImageOptim *.png
    2015-10-31 04:44:40.850 ImageOptim[91993:1330951] Failed to connect (progressBar) outlet from (ImageOptimController) to (NSProgressIndicator): missing setter or instance variable
    CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
    CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.

Despite the warnings, image optimization is successful. Another thing I encountered is symlinking ImageOptim would not work:

    $ ln -s /Applications/ImageOptim.app/Contents/MacOS/ImageOptim /usr/local/bin/ImageOptim
    $ ImageOptim *.png
    2015-10-31 04:52:03.191 ImageOptim[92029:1337326] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting

I'm afraid I don't know how to fix it. It would be cool to have a dedicated command line utility similar to what Sublime Text offers, complete with options and switches.

**Comment by pornel** [comment]
Fixed in 1.6.1: https://imageoptim.com/changelog.html

**Comment by sebastienbarre** [comment]
I'm afraid this is still in 1.6.2

**Comment by TheChrisGlass** [comment]
Still happening on 1.7.1b2

**Comment by confluencepoint** [comment]
Still happening on 1.7.3
